### ISSUE TITLE
Collaboration on similar project

### ISSUE THREAD

**Issue by harveyaa** [sjburwell/fmriprep_denoising#2]
Hi Scott,

We are currently working on a project in our lab called `load_confounds` [https://github.com/SIMEXP/load_confounds](https://github.com/SIMEXP/load_confounds) that has a lot in common with the denoising parts of `fmriprep_denoising`. The timeseries generation is close to another project, `nii-masker` [https://github.com/danjgale/nii-masker](https://github.com/danjgale/nii-masker), that we are also contributing to.You have some cool features and methods implemented that are close to what we are going to be adding.  Eventually, our goal is to have  a clean code base between `load_confounds` and `nii-masker` to denoise preprocessed data and generate timeseries. 

I am reaching out in case you would be interested in working with us on it, specifically  at [Brainhack 2020ish](https://brainhackmtl.github.io/global2020/) that is coming up next week. It is a two week event of half days. I don't know if you have ever participated in Brainhack events, but they are super fun opportunities to meet people in the field and put together a cool project. The registration process is really easy and free! Let me know what you think and if you have any time, I know it's really short notice.

Cheers,

Annabelle

**Comment by sjburwell** [comment]
Hi Annabelle, 

I am very sorry to have missed this request. I hope you enjoyed BrainHack - I've heard it's a good hackathon! I have been quite underwater with a mobile EEG project I've been working on, and this issue went unnoticed. If you'd like to discuss future collaborations or have suggestions for this repos code, I'm open to them! 

Best,
Scott
